- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `sudo kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp | wc -l` -gt 0 ]; then  
            sudo kubectl delete deploy `sudo kubectl get deploy | grep -v NAME | awk '{print $1}' | grep myapp`
         else 
            echo "No app deployments found"
         fi
         if [ `sudo kubectl get svc | grep myapp-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            sudo kubectl delete svc `sudo kubectl get svc | grep myapp-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy app
      shell: sudo kubectl create deploy myapp --image=vidyadhards/samplejavaapp:{{ build }}
    - name: increase replicas 
      shell: sudo kubectl scale deploy myapp --replicas=2
    - name: deploy service
      shell: sudo kubectl expose deploy myapp --name myapp-svc --port 8080 --type NodePort
